version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 5
    labels:
      - "ci-cd"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "08:00"
    open-pull-requests-limit: 5
    labels:
      - "ci-cd"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "08:00"
    open-pull-requests-limit: 5
    labels:
      - "ci-cd"
    commit-message:
      prefix: "chore"
