MD013: false # Отключить ограничение на длину строки
MD033: false # Разрешить inline HTML
MD024: false # Разрешить дублирующиеся заголовки
MD029: false # Разрешить нумерацию 1. 2. 3. в списках (вместо 1. 1. 1.)
MD034: false # Разрешить голые URL без скобок <>
MD041: false # Отключить требование, чтобы первый элемент был H1
