addSbtPlugin("org.scoverage"      % "sbt-scoverage"            % "2.4.4")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.6.1")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"             % "0.14.7")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.21.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.2")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"                  % "0.4.8")
