package dicechess.engine.search

import io.circe.generic.auto.*
import io.circe.parser.decode
import java.io.{File, PrintWriter}
import java.net.URLEncoder
import scala.io.Source

/** Executable task to dynamically generate visual documentation for KingCaptureProbability test cases.
  */
object KingCaptureDocGenerator:

  private def loadTestCases(resourcePath: String): List[KingCaptureProbabilityTestCase] =
    val source = Option(getClass.getClassLoader.getResourceAsStream(resourcePath))
      .map(Source.fromInputStream)
      .getOrElse(sys.error(s"Resource not found: $resourcePath"))
    val jsonStr = try source.mkString
    finally source.close()
    decode[KingCaptureProbabilityTestSuite](jsonStr) match
      case Right(suite) => suite.testCases
      case Left(error)  => sys.error(s"Failed to parse $resourcePath: $error")

  def main(args: Array[String]): Unit =
    println("Starting documentation generation for KingCaptureProbability Test Cases...")

    val resourcePath = "search/king_capture_probabilities.json"
    val cases        = loadTestCases(resourcePath)

    val sb = new StringBuilder()
    sb.append("---\n")
    sb.append("title: King Capture Probability Test Cases\n")
    sb.append("description: Visual catalog of expert-vetted test cases for king capture probability analysis.\n")
    sb.append("sidebar:\n")
    sb.append("  order: 2\n")
    sb.append("---\n\n")
    sb.append("<!-- @generated by KingCaptureDocGenerator.scala - do not edit directly -->\n\n")

    sb.append(
      "This page catalogs all our active test cases for king capture probability, allowing developers to visually inspect and verify scenarios.\n\n"
    )

    for (tc, index) <- cases.zipWithIndex do
      val caseNum = index + 1

      // Generate Lichess FEN image URL — strip the 7th dice field (not part of standard FEN)
      val standardFen = tc.fen.split(" ").take(6).mkString(" ")
      val cleanFen    = standardFen.replace(' ', '_')
      val encodedFen  = URLEncoder.encode(cleanFen, "UTF-8")
      val boardColor  = if tc.fen.split(" ").lift(1).contains("w") then "white" else "black"
      val imgUrl      =
        s"https://lichess1.org/export/fen.gif?fen=$encodedFen&color=$boardColor&theme=brown&piece=cburnett"

      sb.append(s"## $caseNum. ${tc.name}\n\n")
      sb.append(
        s"""<div style="display: flex; flex-direction: row; gap: 24px; align-items: start; margin-bottom: 30px; flex-wrap: wrap;">
  <div style="flex: 1; min-width: 300px;">
    <p style="margin-top: 0; margin-bottom: 16px;">${tc.description}</p>
    <ul style="list-style-type: disc; padding-left: 20px; margin-bottom: 0;">
      <li style="margin-bottom: 8px;"><strong>Expected Probability:</strong> <code>${f"${tc.expectedKingProbability * 100}%.2f%%"}</code></li>
      <li style="margin-bottom: 0;"><strong>FEN:</strong> <code>${tc.fen}</code></li>
    </ul>
  </div>
  <div style="flex: 0 0 280px; width: 280px; min-width: 280px; margin: 0 auto;">
    <img src="$imgUrl" alt="Board Position" style="width: 100%; border-radius: 8px; box-shadow: 0 4px 10px rgba(0,0,0,0.15); border: 1px solid rgba(0,0,0,0.08);" />
  </div>
</div>

---

"""
      )

    // Write to Astro docs content folder
    val outputFile = new File("docs/src/content/docs/architecture/search/02-king-capture-probability-test-cases.md")
    outputFile.getParentFile.mkdirs()

    val pw = new PrintWriter(outputFile)
    try
      pw.print(sb.toString())
      println(s"Successfully generated visual test cases catalog at: ${outputFile.getAbsolutePath}")
    catch
      case e: Exception =>
        println(s"Failed to write to ${outputFile.getAbsolutePath}: ${e.getMessage}")
    finally pw.close()
