name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'
          cache: sbt
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Show sbt version
        run: sbt --version
      - name: scalafmt check
        run: sbt scalafmtCheckAll
      - name: Run tests
        run: sbt test
