name: Deploy Documentation to Pages

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'src/main/scala/**'
      - '.github/workflows/deploy-docs.yml'

  # Allows manual execution from Actions tab
  workflow_dispatch:


# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  BUILD_PATH: "./docs"

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.0.0
        with:
          distribution: temurin
          java-version: '21'
          cache: sbt

      - name: Setup sbt
        uses: sbt/setup-sbt@93e926cbdb4a428e41b4ef754124ec82925ffdc2 # v1.1.5

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.2.2
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "${{ env.BUILD_PATH }}/package-lock.json"

      - name: Install Node Dependencies
        run: npm ci
        working-directory: ${{ env.BUILD_PATH }}

      - name: Build with Astro
        run: npm run build
        working-directory: ${{ env.BUILD_PATH }}

      - name: Generate Scaladoc
        run: sbt doc

      - name: Merge Scaladoc into Astro dist
        run: |
          mkdir -p ${{ env.BUILD_PATH }}/dist/api
          cp -r jvm/target/scala-3.8.3/api/* ${{ env.BUILD_PATH }}/dist/api/

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "${{ env.BUILD_PATH }}/dist"

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy static site to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
