name: "CD: Deploy Documentation"

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'src/main/scala/**'
      - 'jvm/src/test/resources/search/**'
      - 'shared/src/test/resources/movegen/**'
      - '.github/workflows/deploy-docs.yaml'

  # Allows manual execution from Actions tab
  workflow_dispatch:


# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  BUILD_PATH: "./docs"

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'
          cache: sbt

      - name: Setup sbt
        uses: sbt/setup-sbt@93e926cbdb4a428e41b4ef754124ec82925ffdc2

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "26"
          cache: "npm"
          cache-dependency-path: "${{ env.BUILD_PATH }}/package-lock.json"

      - name: Install Node Dependencies
        run: npm ci
        working-directory: ${{ env.BUILD_PATH }}

      - name: Generate Visual Test Cases Catalog
        run: sbt "project rootJVM" "Test / runMain dicechess.engine.movegen.DocGenerator"

      - name: Generate King Capture Probability Test Cases Catalog
        run: sbt "project rootJVM" "Test / runMain dicechess.engine.search.KingCaptureDocGenerator"

      - name: Build with Astro
        run: npm run build
        working-directory: ${{ env.BUILD_PATH }}

      - name: Generate Scaladoc
        run: sbt doc

      - name: Merge Scaladoc into Astro dist
        run: |
          mkdir -p ${{ env.BUILD_PATH }}/dist/api
          cp -r jvm/target/scala-3.8.3/api/* ${{ env.BUILD_PATH }}/dist/api/

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "${{ env.BUILD_PATH }}/dist"

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy static site to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
